# -*- coding: utf-8 -*-
{
    'name': 'Anzamar Multi Theme',
    'version': '2.0',
    'summary': 'Frontend customization for Anzamar Website',
    'description': '',
    'category': 'Website',
    'author': 'Comunitea',
    'website': 'http://www.comunitea.com',
    'license': 'AGPL-3',
    'contributors': [
        'Pavel Smirnov <pavel@comunitea.com>',
        'Rubén Seijas <ruben@comunitea.com>',
    ],
    'depends': [
        'website_base_multi_anz',
    ],
    'data': [
        'data/theme_data.xml',
        'data/website_data.xml',
        'data/menu_data.xml',
        'data/legal_data.xml',
        # 'data/page_data.xml',
        'templates/snippets.xml',
        'templates/head.xml',
        'templates/header.xml',
        'templates/footer.xml',
        'templates/page_home.xml',
        'templates/page_anzamar_group.xml',
        'templates/page_brand_black_laces.xml',
        'templates/page_brand_feel_point.xml',
        'templates/page_brand_goalkers.xml',
        'templates/page_brand_point_sport.xml',
        'templates/page_brand_skipping.xml',
        'templates/page_brand_umbro.xml',
        'templates/page_open_shop.xml',
        'templates/page_work_with_us.xml',
        'templates/shop.xml',
        'templates/product.xml',
        'templates/pages.xml',
        'views/customize_views.xml',
    ],
    'images': [
        '/static/img/anzamar/favicon_anz.png',
    ],
    'qweb': [
    ],
    'installable': True,
    'application': False,
}
